# This file was generated by GoReleaser. DO NOT EDIT.
class Apns2 < Formula
  desc "APNS22 is a CLI tool that helps with sending apns notifications."
  homepage "https://github.com/youjinp/apns2"
  version "0.20.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/youjinp/apns2/releases/download/v0.20.3/apns2_0.20.3_Darwin_x86_64.tar.gz"
    sha256 "e2f6ca1ea4c00149c2340f8b09b8a6382c065d00fb07ea212d666fef08dc5d35"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/youjinp/apns2/releases/download/v0.20.3/apns2_0.20.3_Linux_x86_64.tar.gz"
      sha256 "b286e232d0e95cf8382601230d189dd4cfc665521bb75b43c39031dc8f2bdf04"
    end
  end

  def install
    bin.install "apns2"
  end
end
